# Generated by Django 3.2.6 on 2021-08-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIBASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('ex_range', models.CharField(default='', max_length=20)),
                ('alg_chosen', models.CharField(blank=True, default='', max_length=30)),
                ('time_complexity', models.CharField(max_length=20)),
                ('time_elapsed', models.DateTimeField()),
                ('number_of_primes_returned', models.IntegerField()),
            ],
            options={
                'ordering': ('timeStamp',),
            },
        ),
    ]
